//
// Created by Yorick on 26/10/2016.
//

#ifndef THE_ELDER_CODES_CONSUMABLETYPE_H
#define THE_ELDER_CODES_CONSUMABLETYPE_H
enum class ConsumableType {
    FOOD,
    HEALING,
    ILLUMINATION,
    BOMB,
    TALISMAN,
    COMPASS
};
#endif //THE_ELDER_CODES_CONSUMABLETYPE_H
