//
// Created by Yorick on 27/10/2016.
//

#ifndef THE_ELDER_CODES_INVENTORYSTATE_H
#define THE_ELDER_CODES_INVENTORYSTATE_H
enum class InventoryState {
    STANDBY, EQUIP, USE, DROP, UNEQUIP
};
#endif //THE_ELDER_CODES_INVENTORYSTATE_H
